networks:
  go-mongo:
    driver: bridge

services:
  db:
    container_name: go-mongo_db
    image: mongo:5.0
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - go-mongo
    ports:
      - ${MONGO_PORT}:27017
